# Generated by Django 2.2.7 on 2019-12-02 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('market_open', models.TimeField()),
                ('market_close', models.TimeField()),
                ('time_zone', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_transaction', models.DateTimeField()),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=6, max_digits=18)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticker.Account')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticker.Stock')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='stocks',
            field=models.ManyToManyField(to='ticker.Stock'),
        ),
    ]
