# Generated by Django 2.2.7 on 2019-12-02 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='stocks',
        ),
    ]
